spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "https://twenty-backend.thinkinggms.com/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            client-name: Discord
            redirect-uri: "https://twenty-backend.thinkinggms.com/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - identify
              - email
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id
  datasource:
    url: jdbc:sqlite:data/twenty.db
    driver-class-name: org.sqlite.JDBC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwt:
    secret: ${JWT_SECRET:thisIsDefaultSecretKeyNoWayWowIfYouSeeThisMaybeItsNotWorkingSoDontUseIt}
    expiration: 864000000  # 10일
  oauth2:
    redirectUri: /api/auth/oauth2/redirect  # OAuth2 로그인 성공 후 리다이렉트할 URI

server:
  port: 9487
  forward-headers-strategy: NATIVE
  tomcat:
    # noinspection SpringBootApplicationYaml
    remote-ip-header: X-Forwarded-For
    # noinspection SpringBootApplicationYaml
    protocol-header: X-Forwarded-Proto
    # noinspection SpringBootApplicationYaml
    internal-proxies: .*
  servlet:
    session:
      cookie:
        secure: true